### ISSUE TITLE
Exception 처리 환경 구축

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/backend#2]
## 🔥 Issue
`@ControllerAdvice`를 활용한 예외 처리 환경을 구축한다. 

## ✅ TODO
- [x]  Custom exception template 생성
- [x] `@ControllerAdvice` 기반 exception 처리 환경 구축
  - [x] Custom exception 처리 환경 구축
  - [x] Spring MVC default exception 처리 환경 구축
