### ISSUE TITLE
회원가입 나머지 로직 구현 - 약관 동의, 선호 음식

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/backend#34]
## 🔥 Issue
![Uploading 스크린샷 2023-03-18 02.28.02.png…]()

## ✅ TODO
- [ ] 약관 동의 기능 구현
- [ ] 선호 음식 선택 기능 구현
- [ ] 로그인 시 응답 데이터에 약관 동의, 선호 음식 선택 여부 추가
