### ISSUE TITLE
회원 프로필 이미지 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/backend#64]
## 🔥 Issue
회원 프로필 이미지 구현.

## ✅ TODO
- [x]  필요한 domain class 구현
- [x] 카카오 로그인 중 회원가입 시 `profileImageUrl`을 읽어서 저장할 수 있도록 구현
- [x] 응답 데이터에 프로필 이미지 추가
