### ISSUE TITLE
Table 제약조건, indexing 설정

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/backend#96]
## 🔥 Issue
Table 제약조건과 indexing 설정을 점검하고 추가 적용한다.

## ✅ TODO
- [x]  `varchar` type 글자수 설정
- [x] unique 제약 조건 설정
- [x] not null or nullable 제약 조건 설정
- [x] Indexing 설정

**Comment by Wo-ogie** [comment]
Test 코드에 반영되지 않은 변경사항이 있어 issue reopen.
